version: "3"

services:
  my-mail-api:
    container_name: "my-mail-api"
    image: "my-mail-api"
    build: ..
    ports:
      - "0.0.0.0:3001:3001"
    env_file: ../.env
    environment:
      PORT: 3001
    networks:
      - xosedev
networks:
  xosedev: